### ISSUE TITLE
Error with negative offset and zero-area polygon

### ISSUE THREAD

**Issue by jmw86069** [pmur002/gridgeometry#5]
I'm having trouble with a specific scenario. It's simple, but a little tricky. I think the ideal fix would be within gridGeometry.
(But I could be wrong, and suggestions are welcome ofc!)

Here is a minimal reproducible test:
```R
x1 <- c(4, 5, 4.5, 4)/10;
y1 <- c(4, 5, 4.5, 4)/10;
pathgrob1 <- grid::pathGrob(x=x1, y=y1,
   rule="evenodd",
   gp=grid::gpar(col="navy", fill="red"))
grid::grid.newpage();
grid::grid.draw(pathgrob1);

innergrob1 <- gridGeometry::polyoffsetGrob(
   A=pathgrob1,
   delta=grid::unit(-1, "mm"),
   gp=grid::gpar(col="green", fill="purple"))
grid::grid.draw(innergrob1);
```

The error:
```
Error in x[sapply(x, function(c) length(c$x) > 1)] : 
  invalid subscript type 'list'
```

The problem is caused by a zero-area path. I can use `delta=1` and it works (it expands around the line), but `delta=-1` fails. Makes sense, it cannot shrink a zero-area object.

I could catch the error, except it only happens with `grid.draw()`. The traceback is to `offset.R#100`, within the `xyListPath()` function.

Desired outcome:
This function somehow ignores the error, skips rendering that grob, and continues.

I considered filtering data up-front. It opened other issues, like multi-part polygons. I would need to check the area of every sub-path. I don't want to do that if I can avoid it. (I might try it meanwhile.)

Thank you!

**Comment by pmur002** [comment]
I have added a patch (version 0.4-1, only on github at present).  Hopefully this solves the problem.

**Comment by jmw86069** [comment]
I confirm the patch resolves the error, thank you so much!

In case curious, it was a rare case where a Euler diagram (from `eulerr`) sometimes creates nested circles, and apparently sometimes two circles shared barely enough of an edge that the delta created a "line" - maybe via a rounding error or something. The line works fine otherwise, drawing it appears as a line, etc.
One of my test cases created this scenario without me realizing it, which was great since I realized later it seems to happen more often than I expected. At any rate, now it's good!
Thank you again!

I'll close this issue for convenience, I hope that's alright.
